### ISSUE TITLE
atlas library missing from maven

### ISSUE THREAD

**Issue by ahuret** [bkiers/atlas#6]
Hello, we noticed atlas library is missing from maven:

```
[error] (update) sbt.librarymanagement.ResolveException: Error downloading nl.big-o:atlas:0.2.0
[error]   Not found
[error]   Not found
[error]   not found: /root/.ivy2/local/nl.big-o/atlas/0.2.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/nl/big-o/atlas/0.2.0/atlas-0.2.0.pom
[error]   not found: /root/.m2/repository/nl/big-o/atlas/0.2.0/atlas-0.2.0.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/nl/big-o/atlas/0.2.0/atlas-0.2.0.pom
```

Is there a new location to get it ?

Thank you in advance !

**Comment by jbguerraz** [comment]
@bkiers may you have an idea of what's going on?  thank you a lot!

**Comment by bkiers** [comment]
Yes, I've never uploaded it to Maven Central. Checkout the README, which says you need to do a local `mvn clean install`, after which it'll be available in your local `.m2` Maven folder.

**Comment by bkiers** [comment]
I'd have mentioned this 3 days ago, but @ahuret didn't do an @bkiers, so I didn't see this until now :shrug:

**Comment by jbguerraz** [comment]
thank you! We're ashamed!
Indeed the issue isn't maven related :) our build got broken somehow! Sorry!
